version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: feedback-board-mongodb-dev
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    environment:
      - MONGO_INITDB_DATABASE:${MONGO_DB_NAME}
    volumes:
      - mongodb_data_dev:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/${MONGO_DB_NAME} --quiet
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data_dev:
    driver: local